{
 "title": "FastAPI dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Welcome count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "welcome_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Date count total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "date_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Test page count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "testpage_count_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } }
 ]
}