apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: {{ .Values.ingress.name}}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.service.name}}
            port:
              number: {{ .Values.service.ports.port }}
        path: /
        pathType: Prefix